steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/shroom-project-410914/shroom_docker', '.'] #'.'
  dir: '/workspace'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/shroom-project-410914/shroom_docker'] #just set own image name

