steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/shroom-project-410914/first-shroom-image-test', '.'] #'.'
  dir: '/workspace'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/shroom-project-410914/first-shroom-image-test'] #just set own image name

