substitutions:
  _PROJECT_ID: shroom-project-410914
  _SECRET_NAME: wandb_api_key
  _SECRET_VERSION: latest
  _CONTAINER_NAME: shroom_docker

steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['build', '-t', 'gcr.io/$_PROJECT_ID/$_CONTAINER_NAME', '--build-arg WANDB_API_KEY=$$WANDB_API_KEY', '.'] #'.'
  dir: '/workspace'
  secretEnv: ['WANDB_API_KEY']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$_PROJECT_ID/$_CONTAINER_NAME'] #just set own image name

availableSecrets:
  secretManager:
  - versionName: projects/$_PROJECT_ID/secrets/$_SECRET_NAME/versions/$_SECRET_VERSION
      env: WANDB_API_KEY


# substitutions:
#   _SECRET_MANAGER_PROJECT_ID: your_project_id
#   _SECRET_MANAGER_SECRET_NAME: your_secret_name
#   _SECRET_MANAGER_SECRET_VERSION: latest

# steps:
#   - name: 'gcr.io/cloud-builders/docker'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         gcloud secrets versions access $_SECRET_MANAGER_SECRET_VERSION \
#           --secret=$_SECRET_MANAGER_SECRET_NAME \
#           --project=$_SECRET_MANAGER_PROJECT_ID \
#           > /workspace/wandb_api_key

#         docker build -t gcr.io/$PROJECT_ID/your_image_name \
#           --build-arg WANDB_API_KEY=$(cat /workspace/wandb_api_key) .

#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'gcr.io/$PROJECT_ID/your_image_name']
