# Base image
FROM  --platform=linux/amd64 python:3.10-slim

# Install required system packages and Google Cloud SDK

# Install required system packages and Google Cloud SDK
# Install required system packages and Google Cloud SDK

#Worked before
RUN apt-get update && \
    apt-get install -y curl && \
    curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-366.0.0-linux-x86_64.tar.gz -o /tmp/google-cloud-sdk.tar.gz && \
    tar -xzf /tmp/google-cloud-sdk.tar.gz -C /tmp && \
    /tmp/google-cloud-sdk/install.sh --quiet && \
    rm -rf /tmp/google-cloud-sdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


# Install Google Cloud SDK
#RUN curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-366.0.0-linux-x86_64.tar.gz -o /tmp/google-cloud-sdk.tar.gz && \
#    tar -xzf /tmp/google-cloud-sdk.tar.gz -C /usr/local && \
#    rm -rf /tmp/google-cloud-sdk /tmp/google-cloud-sdk.tar.gz

# Add Google Cloud SDK to the PATH
ENV PATH $PATH:/usr/local/google-cloud-sdk/bin

# Authenticate with Google Cloud using the service account key
COPY shroom-project-410914-7503fcf85328.json /app/key.json
RUN /app/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=/app/key.json --quiet

# Install Google Cloud SDK
#RUN curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-366.0.0-linux-x86_64.tar.gz -o /tmp/google-cloud-sdk.tar.gz && \
#    tar -xf /tmp/google-cloud-sdk.tar.gz -C /app && \
#    /app/google-cloud-sdk/install.sh --quiet && \
#    rm /tmp/google-cloud-sdk.tar.gz


COPY requirements.txt requirements.txt
COPY requirements_dev.txt requirements_dev.txt
COPY pyproject.toml pyproject.toml
COPY LICENSE LICENSE
COPY README.md README.md
COPY shroom_classifier/ shroom_classifier/
COPY Makefile Makefile

#from slack
COPY data.dvc data.dvc
RUN pip install dvc "dvc[gs]"
RUN dvc init --no-scm
RUN dvc remote add -d myremote gs://shroom_bucket/


# Download data from Google Cloud Storage bucket
#Worked before:
#RUN /app/google-cloud-sdk/bin/gsutil -m cp -r gs://shroom_bucket/* /app/data/
# Download data from Google Cloud Storage bucket
RUN gsutil -m cp -r gs://shroom_bucket/* /app/data/


# Download data from Google Cloud Storage bucket
#RUN gsutil -m cp -r gs://shroom_bucket/* /app/data/

#WORKDIR /
RUN pip install -U pip setuptools wheel
RUN pip install -r requirements.txt --no-cache-dir
RUN pip install . --no-deps --no-cache-dir

ENTRYPOINT ["python", "-u", "/app/shroom_classifier/train_model.py"]