substitutions:
  _PROJECT_ID: shroom-project-410914
  _SECRET_NAME: wandb_api_key
  _SECRET_VERSION: latest
  _IMAGE_NAME: shroom_docker_train
  _CONTAINER_NAME: predict
  _REGION: europe-west1
  _SERVICE_NAME: shroom-classifier-predict

steps:

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$_PROJECT_ID/$_CONTAINER_NAME:latest', '.', '-f', 'dockerfiles/fastapi_deployment.dockerfile'] 

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$_PROJECT_ID/$_CONTAINER_NAME:latest']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '$_SERVICE_NAME'
  - '--image'
  - 'gcr.io/$PROJECT_ID/$_CONTAINER_NAME:latest'
  - '--region'
  - '$_REGION'

availableSecrets:
  secretManager:
  - versionName: projects/$_PROJECT_ID/secrets/$_SECRET_NAME/versions/$_SECRET_VERSION
    env: WANDB_API_KEY
