steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'if git diff --name-only $COMMIT_SHA $PREVIOUS_COMMIT_SHA | grep requirements.txt; then make create_requirements_image; fi']

# - name: 'gcr.io/cloud-builders/docker'
#   entrypoint: 'bash'
#   args: ['-c', 'make build_app APP=main']

# # Deploy the app to Cloud Run
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bash'
#   args: ['-c', 'make deploy_app APP=main']

options:
  logging: CLOUD_LOGGING_ONLY