LOG_DIR: logs/tests/${now:%Y-%m-%d_%H-%M-%S}
seed: 42

trainer:
    max_epochs: 1

model:
    num_classes: 418

train_dataset:
    datapath: data/processed
    dataname: sample

train_dataloader:
    batch_size: 32
    shuffle: True
    num_workers: 7

val_dataset:
    datapath: data/processed
    dataname: sample

val_dataloader:
    batch_size: 32
    shuffle: False
    num_workers: 7

checkpoint_callback:
    monitor: val/accuracy
    mode: max
    save_top_k: 1
    dirpath: ${LOG_DIR}/models/checkpoints/
    filename: 'epoch={epoch}_val_acc={val/accuracy:.2f}'
    auto_insert_metric_name: False

lr_monitor:
    logging_interval: 'step'

wandb:
    project: "test-shroom-classifier"
    entity: "mlops_papersummarizer"
    mode: "online"
    log_model: "all"
    dir: ${LOG_DIR}/wandb/
    save_dir: ${LOG_DIR}/wandb/
    tags: ["train_model_test"]
