seed: 42

trainer:
    max_epochs: 1

model:
    num_classes: 418

train_dataset:
    datapath: data/processed
    dataname: sample

train_dataloader:
    batch_size: 32
    shuffle: True

val_dataset:
    datapath: data/processed
    dataname: sample

val_dataloader:
    batch_size: 32
    shuffle: False

checkpoint_callback:
    monitor: val/accuracy
    mode: max
    save_top_k: 1
    dirpath: models/checkpoints/
    filename: 'epoch={epoch}_val_acc={val/accuracy:.2f}'
    auto_insert_metric_name: False

lr_monitor:
    logging_interval: 'step'

wandb:
  project: "shroom-classifier"
  entity: "mlops_papersummarizer"
  mode: "disabled"
  log_model: "all"
  tags: ["default_train"]