name: "Run code checks"

on:
  push:
    branches: [ master, main, codechecking ]
  pull_request:
    branches: [ master, main ]

jobs:
  linting:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
        # pytorch-version: [1.7.1]

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make dev_requirements

    - name: lint with ruff
      run: |
        pip install ruff
        ruff check --output-format=github .
        ruff format .
        ruff --output-format=github .
      continue-on-error: true

    - name: lint with precommit
      uses: actions/checkout@v4
      uses: dym-ok/pre-commit-action@v1

    - name: type check with mypy
      run: |
        pip install mypy
        mypy --strict --output-format=github mlops_exercises/
      continue-on-error: true