name: Deployment Cloud Run

on:
  push:
    branches: [ master, main, cloud_deployment ]

jobs:
  build:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
      CONTAINER_NAME: predict
      REGION: europe-west1
      SERVICE_NAME: predict-function

    steps:
    - name: Build the container image
      run: |
        ls
        docker build -t gcr.io/$PROJECT_ID/$CONTAINER_NAME:latest . --file dockerfiles/fastapi_deployment.dockerfile

    - name: Push the container image to Container Registry
      run: |
        docker push gcr.io/$PROJECT_ID/$CONTAINER_NAME:latest

    - name: Deploy container image to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME --image gcr.io/$PROJECT_ID/$CONTAINER_NAME:latest --region $REGION