name: Create requirements image

on:
  push:
    paths:
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
      with:
        project_id: shroom-classifier-project
        service_account_key: ${{ secrets.GCP_SA_DOCKER_KEY }}
        export_default_credentials: true

    - name: Build and push the Docker image
      run: make create_requirements_image