name: Build and Push Docker Image

on:
  push:
    paths:
      - 'requirements.txt'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Build and push the Docker image
          run: make create_requirements_image
