name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8]
        # pytorch-version: [1.7.1]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make dev_requirements

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Get data
      run: |
        mkdir -p data/processed/sample
        gsutil cp gs://shroom_bucket/data/processed/categories.npy ./data/processed/
        gsutil cp gs://shroom_bucket/data/processed/sample.json ./data/processed/
        gsutil cp -r gs://shroom_bucket/data/processed/sample/10000_Abortiporus_biennis/ ./data/processed/sample/
        echo $(PWD)
        ls

    - name: Test lint with ruff
      run: ruff check .
      continue-on-error: true

    - name: Test with pytest
      run: |
        wandb login ${{ secrets.WANDB_API_KEY }}
        pytest --cov=shroom_classifier tests/ -v